-- MySQL Script generated by MySQL Workbench
-- Mon Mar 24 11:41:34 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema c411_final_project_test_flights
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema c411_final_project_test_flights
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `c411_final_project_test_flights` DEFAULT CHARACTER SET utf8 ;
USE `c411_final_project_test_flights` ;

-- -----------------------------------------------------
-- Table `c411_final_project_test_flights`.`airline`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c411_final_project_test_flights`.`airline` ;

CREATE TABLE IF NOT EXISTS `c411_final_project_test_flights`.`airline` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `code` CHAR(2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `abbreviation_UNIQUE` (`code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c411_final_project_test_flights`.`airport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c411_final_project_test_flights`.`airport` ;

CREATE TABLE IF NOT EXISTS `c411_final_project_test_flights`.`airport` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `code` CHAR(3) NOT NULL,
  `latitude` DECIMAL(9,6) NOT NULL,
  `longitude` DECIMAL(9,6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `abbreviation_UNIQUE` (`code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c411_final_project_test_flights`.`flight_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c411_final_project_test_flights`.`flight_status` ;

CREATE TABLE IF NOT EXISTS `c411_final_project_test_flights`.`flight_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`status` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c411_final_project_test_flights`.`flight`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c411_final_project_test_flights`.`flight` ;

CREATE TABLE IF NOT EXISTS `c411_final_project_test_flights`.`flight` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status_id` INT NOT NULL,
  `airline_id` INT NOT NULL,
  `dep_airport_id` INT NOT NULL,
  `arr_airport_id` INT NOT NULL,
  `scheduled_departure` TIMESTAMP NOT NULL,
  `scheduled_arrival` TIMESTAMP NOT NULL,
  `estimated_arrival` TIMESTAMP NULL,
  `estimated_departure` TIMESTAMP NULL,
  `number` SMALLINT(4) NOT NULL,
  `latitude` DECIMAL(9,6) NULL,
  `longitude` DECIMAL(9,6) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_flight_status_id_idx` (`status_id` ASC) VISIBLE,
  INDEX `fk_flight_airline_id_idx` (`airline_id` ASC) VISIBLE,
  INDEX `fk_flight_dep_airport_id_idx` (`dep_airport_id` ASC) VISIBLE,
  INDEX `fk_flight_arr_aiport_id_idx` (`arr_airport_id` ASC) VISIBLE,
  CONSTRAINT `fk_flight_status_id`
    FOREIGN KEY (`status_id`)
    REFERENCES `c411_final_project_test_flights`.`flight_status` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_flight_airline_id`
    FOREIGN KEY (`airline_id`)
    REFERENCES `c411_final_project_test_flights`.`airline` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_flight_dep_airport_id`
    FOREIGN KEY (`dep_airport_id`)
    REFERENCES `c411_final_project_test_flights`.`airport` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_flight_arr_aiport_id`
    FOREIGN KEY (`arr_airport_id`)
    REFERENCES `c411_final_project_test_flights`.`airport` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

