DELETE FROM flight;
ALTER TABLE flight ALTER COLUMN id RESTART WITH 1;

DELETE FROM flight_status;
ALTER TABLE flight_status ALTER COLUMN id RESTART WITH 1;

DELETE FROM airline;
ALTER TABLE airline ALTER COLUMN id RESTART WITH 1;

DELETE FROM airport;
ALTER TABLE airport ALTER COLUMN id RESTART WITH 1;

DELETE FROM user_search_history;
ALTER TABLE user_search_history ALTER COLUMN ID RESTART WITH 1;